config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length:{ minimum: 8 }
    validates :content, presence: true, length:{ in: 20..5000 }
    
    has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :article_id, presence: true
  validates :author, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_article
  
    def create
      @comment = @article.comments.build(comment_params)
      if @comment.save
        redirect_to @article, notice: "Your comment was created"
      else
        redirect_to @article, notice: "Your comment was not created"
      end
    end
  
    def destroy
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article)
    end
    
    private
    def comment_params
      params.require(:comment).permit(:author, :content)
    end
  
    def set_article
      @article = Article.find(params[:article_id])
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3">
      <%= form.label :title, class:"form-label"%>
      <%= form.text_field :title, class:"form-control" %>
    <div id="emailHelp" class="form-text">Must be at least 8 characters long.</div>
  </div>
  <div class="mb-3">
      <%= form.label :content, class:"form-label"%>
      <%= form.text_area :content, class:"form-control", rows:10 %>
      <div id="emailHelp" class="form-text">Must be between 20 and 5000 characters long.</div>

  </div>

  <%= form.submit class:"btn btn-primary mb-3"%>
<% end %>

app/views/articles/edit.html.erb
<h2 class="my-5">Edit an Article</h2>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article, class:"btn btn-dark"%>
<%= link_to 'Back', articles_path, class:"btn btn-dark" %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<h2 class="my-5">Articles</h2 class="my-5">
<div class="row">
  <% @articles.each do |article| %>
    <div class="col-3">
      <div class="card mb-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= article.title %></h5>
          <h6 class="card-subtitle mb-3 text-muted"><%= article.created_at.strftime("%B %d %Y, %l:%M%P") %></h6>
          <p class="card-text"><%= article.content.truncate(100) %></p>
          <%= link_to "Show More", article , class:"btn btn-dark"%>
          <%= link_to "Edit", edit_article_path(article) , class:"btn btn-dark"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h2 class="my-5">New Article</h2 class="my-5">

<%= render 'form', article: @article %>
<%= link_to 'Go Back', articles_path, class:"btn btn-dark"%>

app/views/articles/show.html.erb
<% if notice %>
<div class="alert alert-success my-3" role="alert">
  <%= notice %>
</div>
<% end %>

<h2 class="my-5"><%= @article.title %></h2>

<p>
  <i><%= @article.content %></i>
</p>

<%= link_to 'Edit', edit_article_path(@article), class:"btn btn-dark" %>
<%= link_to 'Back', articles_path, class:"btn btn-dark"%>

<% if @article.comments.any? %>
  <h2 class="my-5">Comment Section</h2>
  <%= render @article.comments %>
<% end %>

  <h2 class="my-5">Add a Comment</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<div class="row my-3 ">
    <div class="clearfix">
        <strong><%= comment.author %>:</strong>
        <span class="text-muted"><%= comment.content %></span>
        <%= link_to "", article_comment_path(comment.article, comment), method: :delete, class: "btn-close float-end"%>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with( model: [ @article, @article.comments.build ], local: true) do |form| %>

  <div class="mb-3">
      <%= form.label :author, class:"form-label"%>
      <%= form.text_field :author, class:"form-control" %>
  </div>
  <div class="mb-3">
      <%= form.label :content, class:"form-label"%>
      <%= form.text_field :content, class:"form-control" %>
  </div>

  <%= form.submit class:"btn btn-primary mb-3"%>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Leka's Blog", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Home", root_path, class:"nav-link"%>
        </li>
      </ul>
      <form class="d-flex">
        <%= link_to "Add Article", new_article_path, class:"btn btn-primary"%>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Hello, world!</title>
  </head>
  <body>
    <%= render "layouts/navbar"%>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>